name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: priting greeting
        run: echo "Hello World"
      - name: printing goodbye
        run: echo "Goodbye world"
